# Schema for the views plugins of the Indieweb module.

views.field.webmention_bulk_form:
  type: views_field_bulk_form
  label: 'Webmention bulk form'

views.filter.webmention_filter_select:
  type: views.filter.in_operator
  label: 'Webmention select'
  mapping:
    reduce_duplicates:
      type: boolean
      label: 'Reduce duplicate'