indieweb.indieweb_feed.*:
  type: config_entity
  label: 'Feed config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    path:
      type: string
      label: 'The feed path'
    author:
      type: string
      label: 'The feed author'
    jf2:
      type: boolean
      label: 'Whether to expose a JF2 feed'
    relHeader:
      type: boolean
      label: 'Whether to expose the rel="feed" header link'
    relHeaderJf2:
      type: boolean
      label: 'Whether to expose the application/jf2feed+json header link'
    limit:
      type: integer
      label: 'Number of items in feed'
    owner:
      type: integer
      label: 'The user id of the posts for this feed'
    bundles:
      type: sequence
      label: 'The bundles for this feed'
      sequence:
        type: string
