# schema for indieweb.comment
indieweb.comment:
  type: config_object
  label: 'Indieweb comments'
  mapping:
    comment_create_enable:
      type: boolean
      label: 'Enable comment support'
    comment_create_default_status:
      type: integer
      label: 'Default status of a new comment'
    comment_create_comment_type:
      type: string
      label: 'The comment type'
    comment_create_webmention_reference_field:
      type: string
      label: 'The webmention reference field on the comment type'
    comment_create_node_comment_field:
      type: string
      label: 'The comment field on the node type'
    comment_create_send_mail_notification:
      type: email
      label: 'Send mail notification'

# schema for indieweb.indieauth
indieweb.indieauth:
  type: config_object
  label: 'Indieweb indieauth'
  mapping:
    enable:
      type: boolean
      label: 'Enable IndieAuth support'
    expose:
      type: boolean
      label: 'Expose IndieAuth headers'
    authorization_endpoint:
      type: string
      label: 'IndieAuth authorization endpoint'
    token_endpoint:
      type: string
      label: 'IndieAuth token endpoint'

# schema for indieweb.microformats
indieweb.microformats:
  type: config_object
  label: 'Indieweb microformats'
  mapping:
    h_entry:
      type: boolean
      label: 'Enable microformat h-entry class'
    h_event:
      type: string
      label: 'Enable microformat h-event class for a node type'
    post_metadata:
      type: boolean
      label: 'Enable microformat metadata classes like dt-published and u-url'
    p_name_exclude_node_type:
      type: string
      label: 'Node type on which p-name will not be printed'
    e_content:
      type: boolean
      label: 'Enable microformat e-content class'
    u_photo:
      type: boolean
      label: 'Enable microformat u-photo class'
    u_video:
      type: boolean
      label: 'Enable microformat u-video class'
    p_summary:
      type: text
      label: 'Microformat summary fields'
    p_bridgy_twitter_content:
      type: boolean
      label: 'p-bridgy-twitter-content'

# schema for indieweb.micropub
indieweb.micropub:
  type: config_object
  label: 'Indieweb micropub'
  mapping:
    micropub_enable:
      type: boolean
      label: 'Enable micropub endpoint'
    micropub_add_header_link:
      type: boolean
      label: 'Expose micropub header link'
    micropub_me:
      type: string
      label: 'The url of your website'
    micropub_log_payload:
      type: boolean
      label: 'Whether to log the payload'
    note_create_node:
      type: boolean
      label: 'Enable note support'
    note_status:
      type: integer
      label: 'Whether the note is published or not'
    note_node_type:
      type: string
      label: 'The node type for the note'
    note_content_field:
      type: string
      label: 'The node content field for the note'
    note_upload_field:
      type: string
      label: 'The node upload field for the note'
    note_tags_field:
      type: string
      label: 'The node tags field for the note'
    note_uid:
      type: integer
      label: 'The user id of the note'
    article_create_node:
      type: boolean
      label: 'Enable article'
    article_status:
      type: integer
      label: 'Whether the article is published or not'
    article_node_type:
      type: string
      label: 'The node type for the article'
    article_content_field:
      type: string
      label: 'The node content field for the article'
    article_upload_field:
      type: string
      label: 'The node upload field for the article'
    article_tags_field:
      type: string
      label: 'The node tags field for the article'
    article_uid:
      type: integer
      label: 'The user id of the article'
    like_create_node:
      type: boolean
      label: 'Enable like'
    like_status:
      type: integer
      label: 'Whether the like is published or not'
    like_node_type:
      type: string
      label: 'The node type for the like'
    like_content_field:
      type: string
      label: 'The node content field for the like'
    like_link_field:
      type: string
      label: 'The node link field for the like'
    like_tags_field:
      type: string
      label: 'The node tags field for the like'
    like_uid:
      type: integer
      label: 'The user id of the like'
    reply_create_node:
      type: boolean
      label: 'Enable reply'
    reply_status:
      type: integer
      label: 'Whether the reply is published or not'
    reply_node_type:
      type: string
      label: 'The node type for the reply'
    reply_content_field:
      type: string
      label: 'The node content field for the reply'
    reply_link_field:
      type: string
      label: 'The node link field for the reply'
    reply_tags_field:
      type: string
      label: 'The node tags field for the reply'
    reply_uid:
      type: integer
      label: 'The user id of the reply'
    repost_create_node:
      type: boolean
      label: 'Enable repost'
    repost_status:
      type: integer
      label: 'Whether the repost is published or not'
    repost_node_type:
      type: string
      label: 'The node type for the repost'
    repost_content_field:
      type: string
      label: 'The node content field for the repost'
    repost_link_field:
      type: string
      label: 'The node link field for the repost'
    repost_tags_field:
      type: string
      label: 'The node tags field for the repost'
    repost_uid:
      type: integer
      label: 'The user id of the repost'
    bookmark_create_node:
      type: boolean
      label: 'Enable bookmark'
    bookmark_status:
      type: integer
      label: 'Whether the bookmark is published or not'
    bookmark_node_type:
      type: string
      label: 'The node type for the bookmark'
    bookmark_content_field:
      type: string
      label: 'The node content field for the bookmark'
    bookmark_link_field:
      type: string
      label: 'The node link field for the repost'
    bookmark_tags_field:
      type: string
      label: 'The node tags field for the bookmark'
    bookmark_uid:
      type: integer
      label: 'The user id of the bookmark'
    event_create_node:
      type: boolean
      label: 'Enable event'
    event_status:
      type: integer
      label: 'Whether the event is published or not'
    event_node_type:
      type: string
      label: 'The node type for the event'
    event_content_field:
      type: string
      label: 'The node content field for the event'
    event_date_field:
      type: string
      label: 'The node link field for the event'
    event_tags_field:
      type: string
      label: 'The node tags field for the event'
    event_uid:
      type: integer
      label: 'The user id of the event'
    rsvp_create_node:
      type: boolean
      label: 'Enable RSVP'
    rsvp_status:
      type: integer
      label: 'Whether the RSVP is published or not'
    rsvp_node_type:
      type: string
      label: 'The node type for the RSVP'
    rsvp_content_field:
      type: string
      label: 'The node content field for the RSVP'
    rsvp_link_field:
      type: string
      label: 'The node link field for the RSVP'
    rsvp_rsvp_field:
      type: string
      label: 'The node RSVP field for the RSVP'
    rsvp_tags_field:
      type: string
      label: 'The node tags field for the rsvp'
    rsvp_uid:
      type: integer
      label: 'The user id of the RSVP'

field.formatter.settings.link_microformat:
  type: field.formatter.settings.link
  label: 'Link microformat format settings'
  mapping:
    microformat_class:
      type: string
      label: 'The microformat class for the link'


# schema for indieweb.microsub
indieweb.microsub:
  type: config_object
  label: 'Indieweb microsub'
  mapping:
    enable:
      type: boolean
      label: 'Expose microsub endpoint'
    microsub_endpoint:
      type: string
      label: 'Microsub endpoint'

# schema for indieweb.publish
indieweb.publish:
  type: config_object
  label: 'Indieweb publish'
  mapping:
    channels:
      type: text
      label: 'Channels to publish to'
    back_link:
      type: string
      label: 'How to handle Bridgy back links'
    publish_custom_url:
      type: boolean
      label: 'Expose dynamic URL textfield'
    publish_link_fields:
      type: string
      label: 'Fields to use'
    publish_send_webmention_by:
      type: string
      label: 'How to handle the webmention send queue'
    publish_log_response:
      type: boolean
      label: 'Whether to log the response of the publish call'

# schema for indieweb.webmention
indieweb.webmention:
  type: config_object
  label: 'Indieweb webmention'
  mapping:
    webmention_endpoint:
      type: string
      label: 'Webmention endpoint'
    webmention_secret:
      type: string
      label: 'Webmention secret'
    pingback_endpoint:
      type: string
      label: 'Pingback endpoint'
    webmention_enable:
      type: boolean
      label: 'Whether to allow webmentions'
    pingback_enable:
      type: boolean
      label: 'Whether to allow pingbacks'
    webmention_uid:
      type: integer
      label: 'The user id of the article'
    webmention_log_payload:
      type: boolean
      label: 'Whether to log the payload'
