# schema for indieweb_context.settings
indieweb_context.settings:
  type: config_object
  label: 'Indieweb post contexts'
  mapping:
    handler:
      type: string
      label: 'How to fetch post contexts'

# schema for indieweb node type settings
node.type.*.third_party.indieweb_context:
  type: mapping
  label: 'Per-content type IndieWeb settings'
  mapping:
    post_context_link_field:
      type: string
      label: 'Link field'
    post_context_post_type:
      type: string
      label: 'Type of post'
